name: "Pull Request"
on: pull_request
jobs:
  pr-check:
    name: "Pull Request Check"
    uses: mParticle/mparticle-workflows/.github/workflows/android-kit-pull-request.yml@main
    with:
      branch_name: ${{ github.head_ref }}

  pr-notify:
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false
    needs:
      - pr-check
    name: Notify GChat
    uses: ROKT/rokt-workflows/.github/workflows/oss_pr_opened_notification.yml@main
    secrets:
      gchat_webhook: ${{ secrets.GCHAT_PRS_WEBHOOK }}
